<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\\DashboardPortal.Application\\DashboardPortal.Application.csproj" />
    <ProjectReference Include="..\\DashboardPortal.Infrastructure\\DashboardPortal.Infrastructure.csproj" />
  </ItemGroup>
</Project>
